name: flutterdemo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  path_provider: 0.3.0
  video_player: 0.5.2
  camera: 
  audioplayer:
  flutter_tts:
  url_launcher:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/container/pic1.jpg
    - images/container/pic2.jpg
    - images/container/pic3.jpg
    - images/container/pic4.jpg
    - images/grid/pic1.jpg
    - images/grid/pic2.jpg
    - images/grid/pic3.jpg
    - images/grid/pic4.jpg
    - images/grid/pic5.jpg
    - images/grid/pic6.jpg
    - images/grid/pic7.jpg
    - images/grid/pic8.jpg
    - images/grid/pic9.jpg
    - images/grid/pic10.jpg
    - images/grid/pic11.jpg
    - images/grid/pic12.jpg
    - images/grid/pic13.jpg
    - images/grid/pic14.jpg
    - images/grid/pic15.jpg
    - images/grid/pic16.jpg
    - images/grid/pic17.jpg
    - images/grid/pic18.jpg
    - images/grid/pic19.jpg
    - images/grid/pic20.jpg
    - images/grid/pic21.jpg
    - images/grid/pic22.jpg
    - images/grid/pic23.jpg
    - images/grid/pic24.jpg
    - images/grid/pic25.jpg
    - images/grid/pic26.jpg
    - images/grid/pic27.jpg
    - images/grid/pic28.jpg
    - images/grid/pic29.jpg
    - images/grid/pic30.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
